# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OptimalCustomRoute
                                 A QGIS plugin
 An optimal custom route
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-20
        copyright            : (C) 2024 by AgataPalma PedroMorais
        email                : a2023113935@isec.pt
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OptimalCustomRoute class from file OptimalCustomRoute.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .optimal_custom_route import OptimalCustomRoute
    return OptimalCustomRoute(iface)
